version: '3'

services:
  php:
    from: php:8.1-fpm
    # build:
    #   context: ./php
    #   dockerfile: Dockerfile
    volumes:
      - ./:/app
    # ports:
    #   - "9000:9000"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
